version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  cg-master:
    image: zelejs/cg-master:latest
    container_name: cg-master
    build:
      context: .
    #ports: 
    #  - 8080:8080

networks: 
  default:
    sandbox_network:
