version: "3"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  cg-master:
    image: cg-master:latest
    container_name: cg-master
    build:
      context: .
      dockerfile: ./Dockerfile
    # volumes: 
    #   - ./api:/webapps
    ports: 
      - 8080:8080

# networks: 
#   default:
#     external: 
#       name: sandbox_network
