version: "3.4"
# COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
services:
  cg-master:
    image: cg-master:latest
    container_name: cg-master
    build:
      context: ../.
      dockerfile: ./Docker/Dockerfile
    ports: 
      - 8080:8080

networks: 
  default:
    external: 
      name: sandbox_network
