version: "3.4"
services:
  cg-master:
    image: cg-master:latest
    container_name: cg-master
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080

# networks: 
#   default:
#     external: 
#       name: sandbox_network
